---
ssh_public_keys:
  - key: id_rsa
    value: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMPnnSzwBK0Qb7JV1q9KsUCmsXzlxZ1SSxKflvGSSMOFoJYlyAvxFkDOVxQZllddLJWC4P2XKhEF7vMhQ5jCe8rxWFqznUCfadR1yRZBXxZd+Jzy48a3ZD/b/WwO3su/R9OPpK5lQZJFjfeVxg5bIKXCYxkXAx85oeKp9LPpq6JPbXYeagZxd2+TUUjo2goPbD7hPTlSDZYhZBXnBTWodhqbRQ71T8nMU946c5KtqQisa9QR7xDr9bACWdxfjKSZVQp9O1kTzeI1jYsinKc3n6La6Ur0xG85fwxmNUhhAfMQJmxS39hXbUo1UAqVxoc/Uf4/gVaTJWnQN6WEgl4keJ camm
